config/routes.rb
Rails.application.routes.draw do
  root to: "movies#index"
  resources :movies, only: [:index, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.order(year: :desc, title: :asc)

    if params[:query].present?
      @movies = @movies.where("title ILIKE ?", "%#{params[:query]}%")
      # @movies = Movie.search_by_title(params[:query])
    end
    # Por defecto todas las acciones de RoR devuelven SIEMPRE HTML
    respond_to do |format|
      format.html
      format.text { render partial: "movies/list", locals: {movies: @movies}, formats: :html}
    end
  end

  def update
    @movie = Movie.find(params[:id])
    @movie.update(movie_params)

    respond_to do |format|
      format.html
      format.text { render partial: "movies/movie_infos", locals: { movie: @movie }, formats: :html}
    end
  end

  private 

  def movie_params
    params.require(:movie).permit(:title, :year)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FromDesignToCode</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/_list.html.erb
<div data-search-movies-target="list">
  <p class="h3">
    <% if params[:query].blank? %>
      <%= pluralize movies.count, "movie" %> available
    <% else %>
      <%= pluralize movies.count, "result" %> for <code><%= params[:query] %></code>
    <% end %>
  </p>
  <div class="movies">
    <% movies.each do |movie| %>
      <%= render "movie_infos", movie: movie %>
    <% end %>
  </div>
</div>

app/views/movies/_movie_infos.html.erb
<div class="movie-card" data-controller="edit-movie" data-edit-movie-target="infos">
  <%= image_tag movie.image_url %>

  <div class="movie-infos">
    <h2><%= movie.title %><small> (<%= movie.year %>)</small></h2>
    <button aria-label="Edit movie" data-action="click->edit-movie#displayForm">
      <i class="fa-solid fa-pen fa-xs ml-2"></i>
    </button>
  </div>

  <%= simple_form_for movie, html: {
    class: "d-none",
    data: { 
      edit_movie_target: "form",
      action: "submit->edit-movie#update"
      }
    } do |f| %>
    <%= f.input :title %>
    <%= f.input :year %>
    <%= f.submit "Update movie", class: "btn btn-sm btn-primary btn-block mt-2" %>
  <% end %>
</div>

app/views/movies/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1 class="h2 my-3 d-flex justify-content-center">Movies to watch 🍿</h1>

      <div data-controller="search-movies">
        <%= form_with url: movies_path, method: :get, html: {
          class: "mb-4",
          data: {search_movies_target: "form"}
          } do |f| %>
          <%= f.label :query, "Type a movie title" %>
          <%= f.text_field :query,
                           class: "form-control",
                           value: params[:query],
                           data: {
                            search_movies_target: "input",
                            action: "keyup->search-movies#search"
                            }
                           %>
        <% end %>

        <%= render "list", movies: @movies %>
      </div>
    </div>
  </div>
</div>